name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Replace with the branch that triggers deployment if needed

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest  # Changed to Windows runner

  deploy:
    runs-on: windows-latest  # Changed to Windows runner
    steps:
      - uses: actions/checkout@v3  # Checks out your code from GitHub
      - uses: suborbital/flutter@v1  # Installs Flutter SDK
        with:
          flutter-version: 'latest'  # Using latest compatible Flutter version
      - uses: google/firebase-tools@v11  # Installs Firebase CLI
      - run: echo "// FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" >> %GITHUB_ENV%  # Adds service account key for Windows (using %)
      - run: icacls %GITHUB_ENV% /grant Administrators:(OI)(CI)F  # Sets read permissions for the environment variable (security)
      - run: firebase login --project ${{ secrets.FIREBASE_PROJECT_ID }}  # Logs in to Firebase using project ID and service account key
      - run: flutter build web --release  # Builds the Flutter web app in release mode
      - run: firebase deploy --only hosting  # Deploys the built web app to Firebase Hosting
