name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Replace with the branch that triggers deployment if needed

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest  # Build runs on a Windows runner

  deploy:
    runs-on: windows-latest  # Deployment runs on a Windows runner
    steps:
      - uses: actions/checkout@v3  # Checks out your code from GitHub
      - uses: suborbital/flutter@v1  # Installs Flutter SDK
        with:
          flutter-version: 'latest'  # Using latest compatible Flutter version
      - uses: google/firebase-tools@v11  # Installs Firebase CLI

      # (Optional) Secret Check (adjust based on your CI platform)

      - run: flutter build web --release
        shell: bash  # Use a shell that captures exit codes
        # Add error handling based on exit code (optional)

      - run: firebase deploy --only hosting
        shell: bash  # Use a shell that captures exit codes
        # Add error handling based on exit code (optional)
